# Print a new line at the start of the prompt
add_newline = true

[character]
# ğŸŒ ğŸŒ› â™ ğŸ’ ğŸ™ ä·•  âˆ´
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 1

[time]
disabled = false

[hostname]
format = " on [$hostname]($style) in "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[username]
format = "[$user]($style)"
